package net.mrgoddavid.minecraftthestoriesmod;

import net.fabricmc.api.ModInitializer;

import net.fabricmc.fabric.api.loot.v3.LootTableEvents;
import net.mrgoddavid.minecraftthestoriesmod.advancement.MtsAdvancementTriggers;
import net.mrgoddavid.minecraftthestoriesmod.block.MtsBlocks;
import net.mrgoddavid.minecraftthestoriesmod.block.entity.MtsBlockEntities;
import net.mrgoddavid.minecraftthestoriesmod.block.menu.MtsMenuTypes;
import net.mrgoddavid.minecraftthestoriesmod.creativemodetab.CreativeModeTabs;
import net.mrgoddavid.minecraftthestoriesmod.item.MtsItemModelTemplates;
import net.mrgoddavid.minecraftthestoriesmod.item.MtsItems;
import net.mrgoddavid.minecraftthestoriesmod.loot.MtsLootTableModifiers;
import net.mrgoddavid.minecraftthestoriesmod.test.MtsTestWorldServer;
import net.mrgoddavid.minecraftthestoriesmod.worldgen.MtsWorldGen;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This is the main class of this mod development. I am pretty excited because today is the first mo-dev. :)
 * Hopefully I can survive the sea of Minecraft modding. LWJGL is insanely hard. Perhaps modding as hard as learning
 * LWJGL 3...
 *
 * @author generated by Fabric Mod Template
 * @author Mr. GodDavid
 * @since 8/11/2026
 */
public class MinecraftTheStoriesMod implements ModInitializer {

    public static final String MOD_ID = "minecraft-the-stories-mod";

    // This logger is used to write text to the console and the log file.
    // It is considered best practice to use your mod id as the logger's name.
    // That way, it's clear which mod wrote info, warnings, and errors.
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {
        MtsTestWorldServer.register();
        CreativeModeTabs.registerModCreativeModeTabs();

        MtsItemModelTemplates.registerTemplates();
        MtsMenuTypes.registerMenuTypes();

        MtsItems.registerModItems();
        MtsBlocks.registerModBlocks();
        MtsBlockEntities.registerBlockEntities();

        MtsAdvancementTriggers.register();

        MtsWorldGen.registerWorldGen();

        LootTableEvents.MODIFY.register(MtsLootTableModifiers::modifyLootTables);
    }
}
