package net.mrgoddavid.minecraftthestoriesmod;

import net.fabricmc.fabric.api.datagen.v1.DataGeneratorEntrypoint;
import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator;
import net.mrgoddavid.minecraftthestoriesmod.datagen.ModBlockLootTableProvider;
import net.mrgoddavid.minecraftthestoriesmod.datagen.ModBlockTagsProvider;
import net.mrgoddavid.minecraftthestoriesmod.datagen.ModModelProvider;

/**
 * Generates all JSON files for mod that can be used in vanilla Minecraft.
 *
 * @author generated by Fabric Mod Template.
 * @author Mr. GodDavid
 * @since 8/10/2026
 */
public class MinecraftTheStoriesModDataGenerator implements DataGeneratorEntrypoint {

    @Override
    public void onInitializeDataGenerator(FabricDataGenerator fabricDataGenerator) {
        FabricDataGenerator.Pack pack = fabricDataGenerator.createPack();

        pack.addProvider(ModModelProvider::new);
        pack.addProvider(ModBlockTagsProvider::new);
        pack.addProvider(ModBlockLootTableProvider::new);
    }
}
